account = "siddontang"

# Github Token, see https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
token = ""

repos = [
    "tikv/tikv", 
    "pingcap/pd", 
    "pingcap/raft-rs", 
    "pingcap/grpc-rs",
    "pingcap/rust-prometheus", 
    "pingcap/rust-rocksdb", 
    "pingcap/fail-rs", 
    "pingcap/kvproto",
    "pingcap/go-ycsb",
]

# Slack
# [slack]
# token = ""
# channel = ""
# user = ""